# Pipeline for commits to any branch on github
name: Main Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Node JS
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Component Tests
        run: npm test
